import gbl from "utils/formatter";

export default {
  PyhSeq: "Auto",
  VnCode: "",
  PyhDate: new Date(),
  CurCode: "",
  CurRate: 0,
  DeptPayCode: "",
  PyhAmt: 0,
  PyhAbfTax: 0,
  AppyCode: "",
  PyhRef: "",
  PyhChqFr: "",
  PyhChqTo: "",
  PyhChqDt: null,
  PyhStatus: "Effective",
  PyhClearDt: null,
  PyhPostDt: new Date(),
  PyhClearAmt: 0,
  PyhCr: "",
  PyhDesc: "",
  CurAmt: 0,
  CurPayAmt: 0,
  GainLossDept: "",
  GainLossAcc: "",
  GainLossAmt: 0,
  PayWht: {
    Payee: "",
    Address: "",
    TaxId: "",
    WhtTypeCode: "",
    WhtTotalAmt: 0,
    WhtDeptCode: "",
    WhtRemark1: "",
    WhtRemark2: "",
    WhtNo: "",
    WhtTaxCr: "",
    Items: [],
  },
  DimHList: {
    Dim: [],
  },
  Detail: [],
  WhtDeptCode: "",
  WhtTaxCr: "",
  UserModified: gbl.UserName,
};
