import gbl from "utils/formatter";

export default {
  ArProfileId: 0,
  ArNo: "",
  FirstName: "",
  LastName: "",
  Title: "",
  TaxNo: "",
  RegDate: new Date(),
  Status: "",
  StatusCode: "",
  ArType: "",
  Company: "",
  AddressInfo: {
    Address1: "",
    Address2: "",
    Address3: "",
  },
  Position: "",
  Billto: "Address1",
  Mailto: "Address1",
  Taxto: "Address1",
  Tel: "",
  Fax: "",
  Email: "",
  LateChg: 0,
  CreditTerm: 0,
  CreditLimit: 0,
  Remark: "",
  PaymentCode: "",
  StatementType: "",
  StatementDays: 0,
  StatementDate: 0,
  UserModified: gbl.UserName,
  ARSource: "A/R",
  BranchNo: "",
  Active: true,
  ContractDetail: [],
};
